version: "3.2"

services:
  db:
    image: "danangkusuma/database"
    environment:
      SA_PASSWORD: "Danang123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"  
  api:
    image: danangkusuma/apibangrobert
    ports:
      - "5000:80"